# Generated by Django 5.2.3 on 2025-06-18 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciudad',
            options={'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='direccion',
            options={'ordering': ['ciudad__nombre', 'calle'], 'verbose_name': 'Dirección', 'verbose_name_plural': 'Direcciones'},
        ),
        migrations.AlterModelOptions(
            name='provincia',
            options={'verbose_name': 'Provincia', 'verbose_name_plural': 'Provincias'},
        ),
        migrations.AlterModelOptions(
            name='sucursal',
            options={'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo de documento', 'verbose_name_plural': 'Tipos de documento'},
        ),
        migrations.AlterModelOptions(
            name='tipovehiculo',
            options={'verbose_name': 'Tipo de vehículo', 'verbose_name_plural': 'Tipos de vehículo'},
        ),
        migrations.RemoveField(
            model_name='ciudad',
            name='nombreCiudad',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='nombreProvincia',
        ),
        migrations.AddField(
            model_name='ciudad',
            name='nombre',
            field=models.CharField(default='Sin Nombre', help_text='Nombre descriptivo', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(default='Sin Nombre', help_text='Nombre descriptivo', max_length=50, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='provincia',
            field=models.ForeignKey(help_text='Provincia a la que pertenece la ciudad', on_delete=django.db.models.deletion.CASCADE, related_name='ciudades', to='transporte.provincia', verbose_name='Provincia'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido',
            field=models.CharField(help_text='Apellido del cliente', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.ForeignKey(help_text='Dirección del cliente', on_delete=django.db.models.deletion.CASCADE, related_name='clientes', to='transporte.direccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre del cliente', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nro_documento',
            field=models.PositiveBigIntegerField(help_text='Número de documento del cliente', verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono', max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento del cliente', on_delete=django.db.models.deletion.PROTECT, to='transporte.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='calle',
            field=models.CharField(help_text='Nombre de la calle', max_length=50, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='ciudad',
            field=models.ForeignKey(help_text='Ciudad de la dirección', on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='transporte.ciudad', verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='numero',
            field=models.PositiveIntegerField(help_text='Número de la calle', verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(help_text='Apellido del empleado', max_length=50, verbose_name='Apellido'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.ForeignKey(help_text='Dirección del empleado', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='transporte.direccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_contratacion',
            field=models.DateField(help_text='Fecha en la que fue contratado', verbose_name='Fecha de contratación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(help_text='Nombre del empleado', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nro_documento',
            field=models.PositiveBigIntegerField(help_text='Número de documento del empleado', verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal donde trabaja', on_delete=django.db.models.deletion.CASCADE, related_name='empleados', to='transporte.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='tipo_documento',
            field=models.ForeignKey(help_text='Tipo de documento del empleado', on_delete=django.db.models.deletion.PROTECT, to='transporte.tipodocumento', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='cliente',
            field=models.ForeignKey(help_text='Cliente que recibe el envío', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='transporte.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(help_text='Estado actual del envío', max_length=50, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='fecha_envio',
            field=models.DateTimeField(help_text='Fecha y hora del envío', verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='sucursal',
            field=models.ForeignKey(help_text='Sucursal desde donde se envía', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='transporte.sucursal', verbose_name='Sucursal'),
        ),
        migrations.AlterField(
            model_name='envio',
            name='vehiculo',
            field=models.ForeignKey(help_text='Vehículo que realiza el envío', on_delete=django.db.models.deletion.CASCADE, related_name='envios', to='transporte.vehiculo', verbose_name='Vehículo'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='descripcion',
            field=models.CharField(help_text='Descripción del contenido del paquete', max_length=250, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='dimensiones',
            field=models.DecimalField(decimal_places=2, help_text='Dimensiones totales del paquete', max_digits=10, verbose_name='Dimensiones'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='envio',
            field=models.ForeignKey(help_text='Envío al que pertenece el paquete', on_delete=django.db.models.deletion.CASCADE, related_name='paquetes', to='transporte.envio', verbose_name='Envío'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Peso del paquete en kg', max_digits=10, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='direccion',
            field=models.ForeignKey(help_text='Dirección de la sucursal', on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='transporte.direccion', verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='tipovehiculo',
            name='nombre',
            field=models.CharField(help_text='Nombre descriptivo', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='capacidad_carga',
            field=models.DecimalField(decimal_places=2, help_text='Capacidad máxima de carga', max_digits=10, verbose_name='Capacidad de carga'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='empleado',
            field=models.ForeignKey(help_text='Empleado asignado al vehículo', on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='transporte.empleado', verbose_name='Empleado responsable'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='patente',
            field=models.CharField(help_text='Patente del vehículo', max_length=10, primary_key=True, serialize=False, verbose_name='Patente'),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='tipo_vehiculo',
            field=models.ForeignKey(help_text='Tipo de vehículo', on_delete=django.db.models.deletion.PROTECT, to='transporte.tipovehiculo', verbose_name='Tipo de vehículo'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nro_documento'], name='transporte__nro_doc_81d2ab_idx'),
        ),
    ]
