# Generated by Django 5.2.3 on 2025-06-24 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0002_alter_ciudad_options_alter_direccion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquete',
            name='dimensiones',
        ),
        migrations.AddField(
            model_name='paquete',
            name='alto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Alto del paquete en cm2', max_digits=10, verbose_name='Alto en cm2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='ancho',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ancho del paquete en cm2', max_digits=10, verbose_name='Ancho en cm2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paquete',
            name='longitud',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Longitud del paquete en cm2', max_digits=10, verbose_name='Longitud en cm2'),
            preserve_default=False,
        ),
    ]
