# Generated by Django 5.2.3 on 2025-06-25 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0003_remove_paquete_dimensiones_paquete_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='alto',
            field=models.DecimalField(decimal_places=2, help_text='Alto del paquete en cm', max_digits=10, verbose_name='Alto en cm2'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='ancho',
            field=models.DecimalField(decimal_places=2, help_text='Ancho del paquete en cm', max_digits=10, verbose_name='Ancho en cm2'),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='longitud',
            field=models.DecimalField(decimal_places=2, help_text='Longitud del paquete en cm', max_digits=10, verbose_name='Longitud en cm2'),
        ),
    ]
