# Generated by Django 5.2.3 on 2025-06-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transporte', '0004_alter_paquete_alto_alter_paquete_ancho_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='estado',
            field=models.CharField(choices=[('EN_CAMINO', 'En camino'), ('ENTREGADO', 'Entregado')], default='EN_CAMINO', help_text='Estado actual del envío', max_length=20, verbose_name='Estado'),
        ),
    ]
